version: '3'
services:
  worker:
    build: .
    env_file:
      - .env.dev
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./result:${RESULT_FOLDER}
    depends_on:
      - bot
    command: rq worker-pool --url ${REDIS_URL} -n 3
    networks:
      - app-network

  bot:
    build: .
    volumes:
      - ./uploads:${UPLOAD_DIR}
      - ./result:${RESULT_FOLDER}
      - ./certs:/etc/nginx/certs:ro
    command: python3 bot.py --mode ${MODE} --host ${WEBSERVER_HOST} --port ${WEBSERVER_PORT} --token ${API_TOKEN} --secret ${SECRET_TOKEN} --redis_url ${REDIS_URL} --webhook_host ${WEBHOOK_HOST} --webhook_port ${WEBHOOK_PORT} --webhook_path ${WEBHOOK_PATH} --upload_dir ${UPLOAD_DIR} --result_folder ${RESULT_FOLDER}
    ports:
      - "8081:${WEBSERVER_PORT}"
    depends_on:
      - redis
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://${WEBHOOK_HOST}/health_check"
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: on-failure:health
    networks:
      - app-network

  redis:
    image: redis:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
